name: 継続的インテグレーション/デプロイ

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    name: コード品質チェック
    runs-on: ubuntu-latest
    steps:
      - name: コードのチェックアウト
        uses: actions/checkout@v4

      - name: Bunのセットアップ
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.4

      - name: 依存関係のインストール
        run: bun install

      - name: リント実行
        run: bun run lint

      - name: フォーマットチェック
        run: bun run biome:check

  test:
    name: テスト実行
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: コードのチェックアウト
        uses: actions/checkout@v4

      - name: Bunのセットアップ
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.4

      - name: 依存関係のインストール
        run: bun install

      - name: テスト用データベースの準備
        run: |
          echo "DATABASE_URL=file:./dev-test.db" > .env
          echo "BACKEND_URL=http://localhost:3000" >> .env
          echo "API_BASE_URL=http://localhost:3000/api" >> .env
          echo "PORT=3000" >> .env
          echo "PORT_FRONTEND=5173" >> .env
          echo "FRONTEND_URL=http://localhost:5173" >> .env
          cd database && bun run migrate

      - name: バックエンドテスト実行
        run: bun run test:backend

      - name: フロントエンドテスト実行
        run: bun run test:frontend

  build:
    name: Dockerイメージビルド
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: コードのチェックアウト
        uses: actions/checkout@v4

      - name: Dockerセットアップ
        uses: docker/setup-buildx-action@v3

      - name: バックエンドのビルド
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/backend.Dockerfile
          push: false
          tags: app/backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: フロントエンドのビルド
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/frontend.Dockerfile
          push: false
          tags: app/frontend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # このデプロイジョブは、適切なデプロイ先が設定されている場合にのみコメントを解除
  # deploy:
  #   name: デプロイ
  #   runs-on: ubuntu-latest
  #   needs: build
  #   if: github.ref == 'refs/heads/main'
  #   steps:
  #     - name: コードのチェックアウト
  #       uses: actions/checkout@v4
  #
  #     - name: デプロイツールのセットアップ
  #       # デプロイ先に応じたステップを追加
  #       run: echo "デプロイステップがここに入ります"
